name: live-coding-test
version: "1.0.0"

services:
  dev-db:
    image: postgres
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: new-weather
